[platformio]
default_envs = esp32s3
src_dir = main

[env]
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.extra_component_dirs = components

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1

[env:esp32dev]
platform = espressif32
board = esp32dev