[platformio]
default_envs = esp32c6
src_dir = main

[env]
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.extra_component_dirs = components

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1

[env:esp32c3]
platform = espressif32
board = adafruit_qtpy_esp32c3

[env:esp32dev]
platform = espressif32
board = esp32dev
