[platformio]
default_envs = esp32c6

[env]
framework = espidf
monitor_speed = 115200
build_flags =
    -Imain

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
board_build.partitions = partitions.csv

[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags =
    ${env.build_flags}
    -DESP32_DEV_BOARD
