idf_component_register(
    SRCS "main.c"
         "moisture_sensor.c"
         "display.c"
    INCLUDE_DIRS "."
    REQUIRES "driver"
             "esp_adc"
             "freertos"
             "esp_timer"
             "esp_system"
             "lcd_driver"
             "button_handler"
             "lvgl_port"
             "lvgl"
)